pipeline {
    agent any
    tools {
        maven 'Maven 3.3.3'
    }
    stages {

            stage('Compile') {
                steps {
                    dir('api-itineraries-search') {
                        sh 'mvn clean compile'
                    }
                }

            } 
            stage('Test') {
                steps {
                    dir('api-itineraries-search') {
                        sh 'mvn test'
                    }
                }
            }
            stage('Package') {
                steps {
                    dir('api-itineraries-search') {
                        sh 'mvn -B -DskipTests package'
                    }
                }
            }
    }
}
